### ISSUE TITLE
I'm on a train and I'm bored but I cannot install R on my work computer

### ISSUE THREAD

**Issue by koch-means-cook** [jhorzek/tabelle#13]
The train ride I am currently on is pretty high on the boring-scale. And because I cannot install R on my work computer I cannot work on the package with you.

I would encourage you to solve this problem, as its crucial for the package. Unfortunately I will not be able to help and refuse to elaborate.

Thank you for your work but you will need to do more of it if you want me to use the package...

**Comment by koch-means-cook** [comment]
Nothing changed since I submitted the issue roughly 2min ago...

Any updates??...

**Comment by koch-means-cook** [comment]
Thank you fro addressing this!

**Comment by koch-means-cook** [comment]
I consider this issue closed.

**Comment by jhorzek** [comment]
I think my previous response was not as helpful as it could have been, so I removed it. [ICEs seem to run Linux](https://www.dbsystel.de/dbsystel/Ein-Betriebssystem-fuer-den-ICE--12637776#:~:text=Das%2520Linux%252DBetriebssystem%2520f%C3%BCr%2520die%2520DB&text=Der%2520Clou%2520ist%2520dabei%252C%2520dass,einem%2520eigenen%2520%E2%80%93%2520System%2520betreiben%2520kann.), maybe you can ask your Schaffner if you can install R?
